project_id = "agueqvxkjmllailpoqkd"

[functions.discord-webhook]
verify_jwt = false

[functions.submission-callback]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-ip-ban]
verify_jwt = false

[functions.get-submission-status]
verify_jwt = false